module.exports = {
    prdouctList: "Product list fetched successfully.",
    glassCoveringList: "Glass covering list fetched successfully.",
    productDetail: "Product detail fetched successfully.",
    unableToFound: "Unable to found.",
    validMongoId: "Please provide valid id.",
    productUpdated: "Product details updated successfully.",
    unableToUpadte: "Unable to update.",
    productActivated: "Product has been activated successfully.",
    productDeactivated: "Product has been deactivated successfully.",
    productDuplicated: "Product duplicated successfully.",
    unableToDuplicate: "Unable to duplicate.",
    roomSizeDetail: "Room Size detail fetched successfully.",
    roomSizeUpdated: "Room size updated successfully.",
    partitionDetail: "Partition detail fetched successfully.",
    partitionUpdated: "Partition updated successfully.",
    panelSizeAlready: "Panel size already exist.",
    panelAdded: "Panel added successfully.",
    doorAdded: "Door added successfully.",
    glassCoveringAdded: "Glass covering added successfully.",
    glassCoveringUpdated: "Glass covering updated successfully.",
    unableToSave: "Unable to save.",
    panelList: "Panel list fetched successfully.",
    doorList: "Door list fetched successfully.",
    panelDetail: "Panel detail fetched successfully.",
    panelUpdated: "Panel price updated successfully.",
    panelNotFound: "Panel not found.",
    panelDeleted: "Panel deleted successfully.",
    unableToDelete: "Unable to delete.",
    frameTypeList: "Frame type list fetched successfully.",
    frameVariantList: "Frame variant list fetched successfully.",
    frameTypeUpdated: "Panel updated successfully.",
    frameTypeActivated: "Frame type has been activated successfully.",
    frameTypeDeactivated: "Frame type has been deactivated successfully.",
    frameVariantActivated: "Frame variant has been activated successfully.",
    frameVariantDeactivated: "Frame variant has been deactivated successfully.",
    frameVariantDefaulted: "Frame variant set as default.",
    frameVariantTypeAl: "Frame variant type already exist.",
    frameVariantDelete: "Frame variant deleted successfully.",
    frameVariantAdd: "Frame variant added successfully.",
    frameVariantMaxActive: "You can only activate upto 5 variants.",
    frameVariantDeactiveCheck: "Frame variant unable to deactivate because it is marked as default.",
    handleVariantDeactiveCheck: "Handle variant unable to deactivate because it is marked as default.",
    frameVariantUndefaulted: "Frame variant remove from default.",
    doorChannelList: "Door channel list fetched successfully.",
    doorTypeEnable: "Door type enabled successfully.",
    AtLeastdoorEnable: " At least one door type should be enable.",
    AtLeastCateEnable: "At least one category must be enable.",
    doorTypeDisable: "Door type disabled successfully.",
    doorSizeActivated: "Door size activated successfully.",
    doorSizeDeactivated: "Door size deactivated successfully.",
    doorChannelUpdated: "Door channel updated successfully.",
    doorGlassList: "Door glass list fetched successfully.",
    doorGlassUpdated: "Door glass details updated successfully.",
    doorHingesList: "Door hinges list fetched successfully.",
    doorCategoryEnable: "Door category enabled successfully.",
    doorCategoryDisable: "Door category disabled successfully.",
    doorHingestActivated: "Door hinge activated successfully.",
    doorHingestDeactivated: "Door hinge deactivated successfully.",
    handleSidesList: "Handle sides list fetch successfully.",
    handleSidesActivated: "Handle sides has been activated successfully.",
    handleSidesDeactivated: "Handle sides has been deactivated successfully.",
    handleVariantAdd: "Handle variant added successfully.",
    handleVariantList: "Handle variant list fetched successfully.",
    varientUpdated: "Handle variant details updated successfully.",
    handleVariantActivated: "Handle variant has been activated successfully.",
    handleVariantDeactivated: "Handle variant has been deactivated successfully.",
    handleVariantDefaulted: "Handle variant marked as default.",
    handleVariantUndefaulted: "Handle variant remove from default.",
    handleVariantUpdate: "Handle variant updated successfully.",
    filmList: "Film list fetched successfully.",
    filmAdded: "Film added successfully.",
    filmActivated: "Film activated successfully.",
    filmDeactivated: "Film deactivated successfully.",
    unableToDeactivateFilm: "At least one film must be activated.",
    filmEnable: "Film enabled successfully.",
    filmDisable: "Film disable successfully. ",
    filmName: "Film name already exist.",
    filmUpdated: "Film  details updated successfully.",
    filmDetail: "Film detail fetched successfully.",
    filmDeleted: "Film deleted successfully.",
    provideType: "Please provide type.",
    doorGlassActivated: "Door glass has been activated successfully.",
    doorGlassDeactivated: "Door glass has been deactivated successfully.",
    unableToDeactivate: "At least one product must be activated.",
    unableToActivate: "You can only activate upto 3 products.",
    textureDetail: "Texture details fetched successfully.",
    textureNot: "Texture not found.",
    setDefaultToAnother: "Set default to another one.",
    lenBre: "Linear length and linear width must be 1000 mm to 9000 mm.",
    roomHeight: "Height must be 1500 mm to 3000 mm.",
    breadth: "Breadth must be in between 10 and 40.",
    orderFetched: "Order fetched successfully.",
    orderNotFetched: "Unable to fetch order, please try again.",
    orderNotFound: "Order not found.",
    toleranceFetched: "Tolerance fetched successfully.",
    toleranceUpdated: "Tolerance has been updated successfully.",
    itemAddedToCart: "Item has been added to cart.",
    cartFetched: "Cart has been fetched successfully.",
    cartNotFetched: "Unable to fetch cart, Please try again.",
    itmeNotFound: "Item not found.",
    itemRemoved: "Item has been removed from the cart.",
    cartFull: "Cart has been already full.",
    filmsDisabled: "Films has been disabled successfully.",
    filmsEnabled: "Films has been enabled successfully."
}